development:
  authtoken: <%= ENV['API_TOKEN'] %>
  url: <%= ENV['USERINFO_URL'] %>
  timeout: 10
test:
  authtoken: <%= ENV['API_TOKEN'] %>
  url: <%= ENV['USERINFO_URL'] %>
  timeout: 10
production:
  authtoken: <%= ENV['API_TOKEN'] %>
  url: <%= ENV['USERINFO_URL'] %>
  timeout: 10