development:
  secret: <%= ENV['AUTH_SHARED_SECRET'] %>
  url: <%= ENV['USERINFO_URL'] %>
  timeout: 10
test:
  secret: <%= ENV['AUTH_SHARED_SECRET'] %>
  url: <%= ENV['USERINFO_URL'] %>
  timeout: 10
production:
  secret: <%= ENV['AUTH_SHARED_SECRET'] %>
  url: <%= ENV['USERINFO_URL'] %>
  timeout: 10